/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TratadosRouteImport } from './routes/tratados'
import { Route as SupremaGrandeCapelaRouteImport } from './routes/suprema-grande-capela'
import { Route as RitosRouteImport } from './routes/ritos'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as PrincipiosDaMaconariaRouteImport } from './routes/principios-da-maconaria'
import { Route as OrigemDaMaconariaRouteImport } from './routes/origem-da-maconaria'
import { Route as OrdensParamaconicasRouteImport } from './routes/ordens-paramaconicas'
import { Route as OQueEMaconariaRouteImport } from './routes/o-que-e-maconaria'
import { Route as OGombRouteImport } from './routes/o-gomb'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as MissaoEValoresRouteImport } from './routes/missao-e-valores'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConfrariasRouteImport } from './routes/confrarias'
import { Route as ComoSerMacomRouteImport } from './routes/como-ser-macom'
import { Route as IndexRouteImport } from './routes/index'

const TratadosRoute = TratadosRouteImport.update({
  id: '/tratados',
  path: '/tratados',
  getParentRoute: () => rootRouteImport,
} as any)
const SupremaGrandeCapelaRoute = SupremaGrandeCapelaRouteImport.update({
  id: '/suprema-grande-capela',
  path: '/suprema-grande-capela',
  getParentRoute: () => rootRouteImport,
} as any)
const RitosRoute = RitosRouteImport.update({
  id: '/ritos',
  path: '/ritos',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipiosDaMaconariaRoute = PrincipiosDaMaconariaRouteImport.update({
  id: '/principios-da-maconaria',
  path: '/principios-da-maconaria',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigemDaMaconariaRoute = OrigemDaMaconariaRouteImport.update({
  id: '/origem-da-maconaria',
  path: '/origem-da-maconaria',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensParamaconicasRoute = OrdensParamaconicasRouteImport.update({
  id: '/ordens-paramaconicas',
  path: '/ordens-paramaconicas',
  getParentRoute: () => rootRouteImport,
} as any)
const OQueEMaconariaRoute = OQueEMaconariaRouteImport.update({
  id: '/o-que-e-maconaria',
  path: '/o-que-e-maconaria',
  getParentRoute: () => rootRouteImport,
} as any)
const OGombRoute = OGombRouteImport.update({
  id: '/o-gomb',
  path: '/o-gomb',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const MissaoEValoresRoute = MissaoEValoresRouteImport.update({
  id: '/missao-e-valores',
  path: '/missao-e-valores',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfrariasRoute = ConfrariasRouteImport.update({
  id: '/confrarias',
  path: '/confrarias',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoSerMacomRoute = ComoSerMacomRouteImport.update({
  id: '/como-ser-macom',
  path: '/como-ser-macom',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-ser-macom': typeof ComoSerMacomRoute
  '/confrarias': typeof ConfrariasRoute
  '/contato': typeof ContatoRoute
  '/missao-e-valores': typeof MissaoEValoresRoute
  '/noticias': typeof NoticiasRoute
  '/o-gomb': typeof OGombRoute
  '/o-que-e-maconaria': typeof OQueEMaconariaRoute
  '/ordens-paramaconicas': typeof OrdensParamaconicasRoute
  '/origem-da-maconaria': typeof OrigemDaMaconariaRoute
  '/principios-da-maconaria': typeof PrincipiosDaMaconariaRoute
  '/radio': typeof RadioRoute
  '/ritos': typeof RitosRoute
  '/suprema-grande-capela': typeof SupremaGrandeCapelaRoute
  '/tratados': typeof TratadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-ser-macom': typeof ComoSerMacomRoute
  '/confrarias': typeof ConfrariasRoute
  '/contato': typeof ContatoRoute
  '/missao-e-valores': typeof MissaoEValoresRoute
  '/noticias': typeof NoticiasRoute
  '/o-gomb': typeof OGombRoute
  '/o-que-e-maconaria': typeof OQueEMaconariaRoute
  '/ordens-paramaconicas': typeof OrdensParamaconicasRoute
  '/origem-da-maconaria': typeof OrigemDaMaconariaRoute
  '/principios-da-maconaria': typeof PrincipiosDaMaconariaRoute
  '/radio': typeof RadioRoute
  '/ritos': typeof RitosRoute
  '/suprema-grande-capela': typeof SupremaGrandeCapelaRoute
  '/tratados': typeof TratadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-ser-macom': typeof ComoSerMacomRoute
  '/confrarias': typeof ConfrariasRoute
  '/contato': typeof ContatoRoute
  '/missao-e-valores': typeof MissaoEValoresRoute
  '/noticias': typeof NoticiasRoute
  '/o-gomb': typeof OGombRoute
  '/o-que-e-maconaria': typeof OQueEMaconariaRoute
  '/ordens-paramaconicas': typeof OrdensParamaconicasRoute
  '/origem-da-maconaria': typeof OrigemDaMaconariaRoute
  '/principios-da-maconaria': typeof PrincipiosDaMaconariaRoute
  '/radio': typeof RadioRoute
  '/ritos': typeof RitosRoute
  '/suprema-grande-capela': typeof SupremaGrandeCapelaRoute
  '/tratados': typeof TratadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-ser-macom'
    | '/confrarias'
    | '/contato'
    | '/missao-e-valores'
    | '/noticias'
    | '/o-gomb'
    | '/o-que-e-maconaria'
    | '/ordens-paramaconicas'
    | '/origem-da-maconaria'
    | '/principios-da-maconaria'
    | '/radio'
    | '/ritos'
    | '/suprema-grande-capela'
    | '/tratados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-ser-macom'
    | '/confrarias'
    | '/contato'
    | '/missao-e-valores'
    | '/noticias'
    | '/o-gomb'
    | '/o-que-e-maconaria'
    | '/ordens-paramaconicas'
    | '/origem-da-maconaria'
    | '/principios-da-maconaria'
    | '/radio'
    | '/ritos'
    | '/suprema-grande-capela'
    | '/tratados'
  id:
    | '__root__'
    | '/'
    | '/como-ser-macom'
    | '/confrarias'
    | '/contato'
    | '/missao-e-valores'
    | '/noticias'
    | '/o-gomb'
    | '/o-que-e-maconaria'
    | '/ordens-paramaconicas'
    | '/origem-da-maconaria'
    | '/principios-da-maconaria'
    | '/radio'
    | '/ritos'
    | '/suprema-grande-capela'
    | '/tratados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoSerMacomRoute: typeof ComoSerMacomRoute
  ConfrariasRoute: typeof ConfrariasRoute
  ContatoRoute: typeof ContatoRoute
  MissaoEValoresRoute: typeof MissaoEValoresRoute
  NoticiasRoute: typeof NoticiasRoute
  OGombRoute: typeof OGombRoute
  OQueEMaconariaRoute: typeof OQueEMaconariaRoute
  OrdensParamaconicasRoute: typeof OrdensParamaconicasRoute
  OrigemDaMaconariaRoute: typeof OrigemDaMaconariaRoute
  PrincipiosDaMaconariaRoute: typeof PrincipiosDaMaconariaRoute
  RadioRoute: typeof RadioRoute
  RitosRoute: typeof RitosRoute
  SupremaGrandeCapelaRoute: typeof SupremaGrandeCapelaRoute
  TratadosRoute: typeof TratadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tratados': {
      id: '/tratados'
      path: '/tratados'
      fullPath: '/tratados'
      preLoaderRoute: typeof TratadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suprema-grande-capela': {
      id: '/suprema-grande-capela'
      path: '/suprema-grande-capela'
      fullPath: '/suprema-grande-capela'
      preLoaderRoute: typeof SupremaGrandeCapelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritos': {
      id: '/ritos'
      path: '/ritos'
      fullPath: '/ritos'
      preLoaderRoute: typeof RitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principios-da-maconaria': {
      id: '/principios-da-maconaria'
      path: '/principios-da-maconaria'
      fullPath: '/principios-da-maconaria'
      preLoaderRoute: typeof PrincipiosDaMaconariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origem-da-maconaria': {
      id: '/origem-da-maconaria'
      path: '/origem-da-maconaria'
      fullPath: '/origem-da-maconaria'
      preLoaderRoute: typeof OrigemDaMaconariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens-paramaconicas': {
      id: '/ordens-paramaconicas'
      path: '/ordens-paramaconicas'
      fullPath: '/ordens-paramaconicas'
      preLoaderRoute: typeof OrdensParamaconicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-que-e-maconaria': {
      id: '/o-que-e-maconaria'
      path: '/o-que-e-maconaria'
      fullPath: '/o-que-e-maconaria'
      preLoaderRoute: typeof OQueEMaconariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-gomb': {
      id: '/o-gomb'
      path: '/o-gomb'
      fullPath: '/o-gomb'
      preLoaderRoute: typeof OGombRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missao-e-valores': {
      id: '/missao-e-valores'
      path: '/missao-e-valores'
      fullPath: '/missao-e-valores'
      preLoaderRoute: typeof MissaoEValoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confrarias': {
      id: '/confrarias'
      path: '/confrarias'
      fullPath: '/confrarias'
      preLoaderRoute: typeof ConfrariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ser-macom': {
      id: '/como-ser-macom'
      path: '/como-ser-macom'
      fullPath: '/como-ser-macom'
      preLoaderRoute: typeof ComoSerMacomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoSerMacomRoute: ComoSerMacomRoute,
  ConfrariasRoute: ConfrariasRoute,
  ContatoRoute: ContatoRoute,
  MissaoEValoresRoute: MissaoEValoresRoute,
  NoticiasRoute: NoticiasRoute,
  OGombRoute: OGombRoute,
  OQueEMaconariaRoute: OQueEMaconariaRoute,
  OrdensParamaconicasRoute: OrdensParamaconicasRoute,
  OrigemDaMaconariaRoute: OrigemDaMaconariaRoute,
  PrincipiosDaMaconariaRoute: PrincipiosDaMaconariaRoute,
  RadioRoute: RadioRoute,
  RitosRoute: RitosRoute,
  SupremaGrandeCapelaRoute: SupremaGrandeCapelaRoute,
  TratadosRoute: TratadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
